language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - CODECLIMATE_REPO_TOKEN=860f7ab06f742793290318067352e2ff607282f927e1d535151f60ab737b5faf ./node_modules/.bin/codeclimate < ./coverage/lcov.info
  - rm -rf ./coverage
